main_url = "https://stellarburgers.nomoreparties.site/"
login_url = "https://stellarburgers.nomoreparties.site/login"
forgot_password_url = "https://stellarburgers.nomoreparties.site/forgot-password"
reset_password_url = "https://stellarburgers.nomoreparties.site/reset-password"
profile_url = "https://stellarburgers.nomoreparties.site/account/profile"
order_history_url = "https://stellarburgers.nomoreparties.site/account/order-history"

restore_pass_xpath = "//a[@href='/forgot-password']"
restore_pass_button_xpath = "//button[text()='Восстановить']"
reset_mail_input_xpath = "//input[@type='text']"
input_new_pass_xpath = "//input[@name='Введите новый пароль']"
new_pass_show_xpath = "//div[@class='input__icon input__icon-action']"
new_pass_input_parent_xpath = "//input[@name='Введите новый пароль']/parent::*"
account_link_xpath = "//a[@href='/account']"
input_login_email_xpath = "//input[@type='text']"
input_login_pass_xpath = "//input[@type='password']"
login_button_xpath = "//button[text()='Войти']"
order_history_button_xpath = "//a[text()='История заказов']"