MAIN_URL = "https://stellarburgers.nomoreparties.site/"
LOGIN_URL = MAIN_URL + "login"
FORGOT_PASSWORD_URL = MAIN_URL + "forgot-password"
RESET_PASSWORD_URL = MAIN_URL + "reset-password"
PROFILE_URL = MAIN_URL + "account/profile"
ORDER_HISTORY_URL = MAIN_URL + "account/order-history"
FEED_URL = MAIN_URL + "feed"

RESTORE_PASS_XPATH = "//a[@href='/forgot-password']"
RESTORE_PASS_BUTTON_XPATH = "//button[text()='Восстановить']"
RESET_MAIL_INPUT_XPATH = "//input[@type='text']"
INPUT_NEW_PASS_XPATH = "//input[@name='Введите новый пароль']"
NEW_PASS_SHOW_XPATH = "//div[@class='input__icon input__icon-action']"
NEW_PATH_INPUT_PARENT_XPATH = "//input[@name='Введите новый пароль']/parent::*"
ACCOUNT_LINK_XPATH = "//a[@href='/account']"
INPUT_LOGIN_EMAIL_XPATH = "//input[@type='text']"
INPUT_LOGIN_PASS_XPATH = "//input[@type='password']"
LOGIN_BUTTON_XPATH = "//button[text()='Войти']"
ORDER_HISTORY_BUTTON_XPATH = "//a[text()='История заказов']"
LOGOUT_BUTTON_XPATH = "//button[text()='Выход']"
CONSTRUCTOR_BUTTON_XPATH = "//p[text()='Конструктор']"
FEED_LINK_BUTTON_XPATH = "//p[text()='Лента Заказов']"
INGREDIENT_POPUP_XPATH = "//h2[text()='Детали ингредиента']"
# FIRST_INGREDIENT_XPATH = "//ul[contains(@class,'BurgerIngredients_ingredients__list')][1]/a[1]"
INGREDIENT_BY_NAME_XPATH = "//img[@alt='NAME']/parent::a"
INGREDIENT_POPUP_CLOSE_XPATH = "//section[contains(@class,'Modal_modal_opened')]/div[contains(@class,'Modal_modal__container')]/button"
# INGREDIENT_COUNTER_VALUE_XPATH = "//ul[contains(@class,'BurgerIngredients_ingredients__list')][1]/a[1]/div[1]/p"
INGREDIENT_BY_NAME_COUNTER_XPATH = "//img[@alt='NAME']/parent::a/div[contains(@class,'counter_counter')]/p"
CONSTRUCTOR_BUN_FIRST_DRAGNDROP_XPATH = "//span[text()='Перетяните булочку сюда (верх)']"
ORDER_BUTTON_XPATH = "//button[text()='Оформить заказ']"
# FEED_FIRST_ORDER_XPATH = "//ul[contains(@class,'OrderFeed_list')][1]"
FEED_ORDERS_XPATH = "//ul[contains(@class,'OrderFeed_list')]"
FEED_ORDER_BY_COUNT_XPATH = "//ul[contains(@class,'OrderFeed_list')]/li[ORDERCOUNT]"
FEED_CLOSE_ORDER_POPUP_XPATH = "//section[contains(@class,'Modal_modal_opened')]/div[contains(@class,'Modal_modal__container')]/button"
ORDER_CLOSE_NEW_ORDER_POPUP_XPATH = "//section[contains(@class,'Modal_modal_opened')]/div[contains(@class,'Modal_modal__container')]/button"
# ORDER_HISTORY_FIRST_ORDER_NUMBER_XPATH = "//ul[contains(@class,'OrderHistory_profileList__')]/li[1]/a/div[1]/p[1]"
ORDER_ORDER_NUMBER_BY_ORDER_COUNT_XPATH = "//ul[contains(@class,'OrderHistory_profileList__')]/li[ORDERCOUNT]/a/div[contains(@class,'OrderHistory_textBox')]/p[contains(@class, 'text_type_digits')]"
FEED_ORDER_LIST_XPATH = "//ul[contains(@class,'OrderFeed_list')]/*"
FEED_ORDER_NUMBER_XPATH = "//ul[contains(@class,'OrderFeed_list')]/li[ELEMENTNUMBER]/a/div[contains(@class, 'OrderHistory_textBox')]/p[contains(@class, 'text_type_digits')]"
FEED_ORDERS_TODAY_XPATH = "//p[text()='Выполнено за сегодня:']/parent::div/p[contains(@class, 'OrderFeed_number')]"
FEED_ORDERS_OVERALL_XPATH = "//p[text()='Выполнено за все время:']/parent::div/p[contains(@class, 'OrderFeed_number')]"
FEED_ORDERNUMBER_IN_PROGRESS_XPATH = "//ul[contains(@class, 'OrderFeed_orderListReady')]/li[text()='ORDERNUMBER']"
